# -*- coding: utf-8 -*-
"""doc_genie.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hp6oRY2d91GbmSQF0NQGTQWUUDITrAAh
"""

!pip install gradio reportlab

import ast
import gradio as gr
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet

class DocGenieAnalyzer:

    def extract_function_signature(self, code):

        tree = ast.parse(code)

        functions = []

        for node in ast.walk(tree):

            if isinstance(node, ast.FunctionDef):

                name = node.name
                params = [arg.arg for arg in node.args.args]

                functions.append({
                    "name": name,
                    "parameters": params
                })

        return functions


    def analyze_function_logic(self, code):

        tree = ast.parse(code)

        loops = 0
        conditions = 0
        math_ops = 0

        for node in ast.walk(tree):

            if isinstance(node, (ast.For, ast.While)):
                loops += 1

            if isinstance(node, ast.If):
                conditions += 1

            if isinstance(node, ast.BinOp):
                math_ops += 1

        return loops, conditions, math_ops

def generate_docstring(code, style):

    analyzer = DocGenieAnalyzer()

    try:
        functions = analyzer.extract_function_signature(code)

        loops, cond, math = analyzer.analyze_function_logic(code)

        result = "Function Analysis\n\n"

        result += f"Functions detected: {len(functions)}\n"
        result += f"Loops: {loops}\n"
        result += f"Conditionals: {cond}\n"
        result += f"Math Operations: {math}\n"

        return result

    except Exception as e:
        return f"Error: {str(e)}"

def export_txt(text):

    with open("documentation.txt","w") as f:
        f.write(text)

    return "documentation.txt"

def export_pdf(text):

    styles = getSampleStyleSheet()

    pdf = SimpleDocTemplate("documentation.pdf")

    story = [Paragraph(text, styles["Normal"])]

    pdf.build(story)

    return "documentation.pdf"

with gr.Blocks() as demo:

    gr.Markdown("# DocGenie Code Documentation Tool")

    code_input = gr.Textbox(label="Enter Python Code", lines=15)

    style = gr.Radio(["Google","NumPy"], label="Docstring Style")

    generate = gr.Button("Generate Documentation")

    output = gr.Textbox(label="Documentation Output")

    gr.Markdown("### Export Documentation")

    txt_btn = gr.Button("Download TXT")
    pdf_btn = gr.Button("Download PDF")

    file_output = gr.File(label="Download File")

    generate.click(generate_docstring, inputs=[code_input, style], outputs=output)

    txt_btn.click(export_txt, inputs=output, outputs=file_output)

    pdf_btn.click(export_pdf, inputs=output, outputs=file_output)

demo.launch()